[package]
name = "sawtooth_perf"
version = "0.1.0"
authors = ["Intel Corporation"]

[dependencies]
sawtooth_sdk = { path = "../../sdk/rust" }
protobuf = "1.4.1"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
tokio-timer = "0.1"
